# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-06-17 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdminAplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linea_aerea',
            name='direccion_facebook',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='linea_aerea',
            name='direccion_twitter',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
