# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-05-25 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdminAplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudad',
            name='cod_iata_ciudad',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='pais',
            name='cod_iata_pais',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
