# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-05-28 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdminAplicacion', '0002_auto_20180525_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='codigo_pais',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
