# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-06-18 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdminAplicacion', '0003_auto_20180617_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_itinerario',
            name='fecha_det_iti',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itinerario',
            name='fecha_itinerario',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
