# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-06-18 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appAdminAplicacion', '0004_auto_20180617_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerario',
            name='linea_aerea',
            field=models.ForeignKey(db_column='codigo_linea_aerea', null=True, on_delete=django.db.models.deletion.CASCADE, to='appAdminAplicacion.linea_aerea'),
        ),
    ]
